const locations = {
  northEast: [
    "-Northern New England",
    "Cape Elizabeth",
    "Kennebunk",
    "Hampton",
    "Gloucester",
    "Nantasket",
    "-Southern New England",
    "Cape Cod",
    "Nantucket",
    "Marthas Vineyard",
    "Newport",
    "Block Island",
    "-New York",
    "Montauk",
    "Southampton",
    "Fire Island",
    "Long Beach",
    "Rockaway"
  ],
  midAtlantic: [
    "-New Jersey",
    "Monmouth County",
    "Seaside Heights",
    "Long Beach Island",
    "Atlantic City",
    "Ocean City NJ",
    "Cape May",
    "-Del Marva",
    "Delaware",
    "Ocean City MD",
    "Chincoteague",
    "Eastern Shore",
    "-Virginia Beach / OBX",
    "Virginia Beach",
    "Corolla",
    "Nags Head",
    "Rodanthe",
    "Buxton",
    "Frisco"
  ],
  southEast: [
    "-Southern North Carolina",
    "Cape Lookout",
    "Emerald Isle",
    "Surf City",
    "Wrightsville Beach",
    "Carolina Beach",
    "Holden Beach",
    "-South Carolina",
    "Myrtle Beach",
    "Pawleys Island",
    "Folly Beach",
    "Edisto Beach",
    "Hilton Head",
    "-Georgia",
    "Tybee Island",
    "St Catherines Island",
    "Brunswick"
  ],
  eastFlorida: [
    "-North Florida",
    "Jacksonville Beach",
    "St Augustine",
    "Flagler Beach",
    "New Smyrna",
    "-Central Florida",
    "Cape Canaveral",
    "Cocoa Beach",
    "Indialantic",
    "Sebastian",
    "Fort Pierce",
    "-South Florida",
    "Jupiter",
    "Palm Beach",
    "Delray",
    "Deerfield Beach",
    "Fort Lauderdale",
    "Miami Beach"
  ],
  westFlorida: [
    "-Florida Panhandle",
    "Gulf Shores",
    "Pensacola",
    "Destin",
    "Panama City",
    "Cape San Blas",
    "St George Island",
    "-West Florida",
    "Cedar Key",
    "Clearwater",
    "St Petersburg",
    "Bradenton",
    "Venice",
    "Sanibel Island",
    "Naples"
  ],
  texas: [
    "-North Texas",
    "Galveston",
    "Surfside",
    "Matagorda",
    "-South Texas",
    "Corpus Christi",
    "South Padre Island"
  ],
  northWest: [
    "-Washington",
    "La Push",
    "Westport",
    "Long Beach",
    "-Oregon",
    "Seaside",
    "Rockaway Beach",
    "Newport",
    "Florence",
    "Port Orford",
    "Gold Beach ",
    "Brookings"
  ],
  northernCalifornia: [
    "-California North",
    "Crescent City",
    "Eureka",
    "Fort Bragg",
    "-San Francisco",
    "Sea Ranch",
    "Sonoma County",
    "Marin County",
    "Ocean Beach",
    "Half Moon Bay",
    "Pescadero",
    "Davenport",
    "Santa Cruz",
    "Moss Landing",
    "-Central California",
    "Monterey",
    "Big Sur",
    "San Simeon",
    "Morro Bay",
    "Pismo Beach"
  ],
  southernCalifornia: [
    "-Socal",
    "Santa Barbara",
    "Ventura County",
    "North LA County",
    "South LA County",
    "North Orange County",
    "South Orange County",
    "North SD County",
    "South SD County"
  ],
  hawaii: [
    "-Hawaii (Big Island)",
    "Northeast",
    "Northwest",
    "West",
    "Southeast",
    "-Maui",
    "North(Hookipa)",
    "North(Waiehu)",
    "Upper West(Honolua)",
    "Lahaina",
    "Kihei",
    "Makena",
    "Hana",
    "-Oahu",
    "North Shore",
    "South Shore",
    "Sandy Beach",
    "Ewa Beach",
    "West Side",
    "East Side"
  ]
};

export default locations;